services:
  php:
    build: ./php
    container_name: php-container
    volumes:
      - .:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php